function data = initDataElement( )
% initDataElement generate an initial value
% for data element

    data = struct( ...
        'name', [], ...
        'img',  [], ...
        'pose', [], ...
        'box',  [], ...
        'category', [] );
        
end